### ISSUE TITLE
前端一直加载字体文件，能不能去掉啊

### ISSUE THREAD

**Issue by HCLonely** [soxft/UrlShorting#1]
前端一直加载字体文件，能不能去掉啊
![image](https://user-images.githubusercontent.com/26346802/66209859-f47bca80-e6ea-11e9-9a93-a2fe400f5cd1.png)

**Comment by soxft** [comment]
css使用的是MDUI的css你可以尝试将css下载至本地，然后修改header.php中的css引用地址。
