### ISSUE TITLE
希望能在关闭跳转停留的情况下用301跳转

### ISSUE THREAD

**Issue by kukume** [soxft/UrlShorting#10]
希望能在关闭跳转停留的情况下用301跳转，因为我经常使用短链接来缩短下载直链，如果不是302的话就不可以直接wget下载了

**Comment by soxft** [comment]
可以可以，php貌似header可以做到，有空改改

**Comment by kukume** [comment]
另外大佬，在后台的短域管理，如果内容过长，能不能显示省略号
