### ISSUE TITLE
建议在管理后台可以加入链接编辑

### ISSUE THREAD

**Issue by billy74** [soxft/UrlShorting#12]
非常感谢大神写的这套短域名，简单方便 
有个小建议就是希望可以在后台进行对已生成的短链进行编辑，可以自主的修改跳转就完美了
还有就是在API中能否加入一个用户toekn 防止没有授权的用户生成

**Comment by soxft** [comment]
可以可以，下一个版本国庆节的时候修改，要添加/优化挺多功能
