### ISSUE TITLE
Error at first connection

### ISSUE THREAD

**Issue by 1qc1q** [soxft/UrlShorting#27]
Hello, I have an error after the install on the login.php page :
Notice: Undefined index: password in /mysite.com/short/admin/login.php on line 17

And try direct at index.php and other error
Notice: Undefined index: id in /mysite.com/short/header.php on line 15

Help me please !

**Comment by soxft** [comment]
Hi. This project has not been maintained for a long time and it does not support versions above php 7.4. 
You can try to use php 7.1~7.3
