### ISSUE TITLE
能不能自定义

### ISSUE THREAD

**Issue by logdns** [soxft/UrlShorting#4]
能不能自定义短网址后面

**Comment by soxft** [comment]
暂时不行吧，以后可能会增加，还有你这头像哈哈哈哈

**Comment by logdns** [comment]
好吧  我还想着你添加一下 呜呜  我刚刚在github搜索到你的项目

^_^

**Comment by soxft** [comment]
啊哈，为什么要自定义呢

**Comment by logdns** [comment]
其实 我就是想搭建个自己用的 长网址 缩短成 自己自定义的短网址.
例如
原  https://github.com/soxft/URLshorting/issues/4 
新 https://t.mysite.com/4
或者 https://t.mysite.com/自定义

随机生成总感觉少点啥

感觉解答

**Comment by soxft** [comment]
那下个版本看情况给加上，主要因为没学过css所以加个输入框可能加上会看起来挺别扭的哈😂

**Comment by soxft** [comment]
其实可以自己在数据库里添加的

**Comment by logdns** [comment]
请教一下 数据库里如何添加
 格式是啥样的

**Comment by soxft** [comment]
这样吧，你发邮件给我contact#xcsoft.top发下你的qq？？我加qq和你说，可能方便点
