### ISSUE TITLE
新功能提议：允许用户自定义短链后缀

### ISSUE THREAD

**Issue by pplulee** [soxft/UrlShorting#5]
可以加入允许用户自定义的功能
并且core部分不需要对shorturl和passmessage的短链生成分为两部分，导致代码冗长

我已经在自己的fork中测试，如果作者同意，希望可以给我开个pr

**Comment by soxft** [comment]
可以，感谢您的建议，但是考虑到未来开发等问题以及我对Git其实不太熟悉（（尴尬，所以希望理解😂））就不pr了😂 目前正在调试修改新版本

**Comment by pplulee** [comment]
没关系，你按照自己的进度就可以
顺便提个对core.php的优化方案，可以参考[此处](https://github.com/pplulee/UrlShorting/blob/master/app/core.php)
就不需要对passmassage和shorturl分两块处理

**Comment by soxft** [comment]
你可以参考一下 目前的demo（dwwz.xyz）看一下体验如何，同时想问一下对于自定义短域你觉得是必须限制输入位数为管理员设置的，还是给定一个特定的范围区间

**Comment by pplulee** [comment]
我觉得整体功能挺好的，实用就完事了
我是按照shortny那个方向的

关于长度，我觉得其实没什么关系，重复概率很低的，所以为了方便还是预设比较好

**Comment by soxft** [comment]
好的，感谢
