### ISSUE TITLE
二维码建议使用js生成

### ISSUE THREAD

**Issue by cnhongv** [soxft/UrlShorting#6]
个人建议，二维码没有必要在服务器端生成，完全可以通过调用开源的js版Qrcode库在客户端生成，可参考：[https://github.com/jeromeetienne/jquery-qrcode](https://github.com/jeromeetienne/jquery-qrcode) 或者 [https://github.com/kazuhikoarase/qrcode-generator](https://github.com/kazuhikoarase/qrcode-generator)

**Comment by soxft** [comment]
之前的确尝试过使用qrcode库，但是考虑到api调用时需要返回qrcode的图片地址所以选择了使用phpqrcode，不过使用javascript在客户端生成的话的确比较节省服务器资源，下个版本会考虑使用，感谢您的建议

**Comment by essesoul** [comment]
相关功能已添加
